name: dio_adapter
description: A Dart package for simplifying HTTP requests using Dio, with customizable handling for API CRUD operations and errors.
version: 1.9.0
repository: https://github.com/ahmedtalal/dio_adapter

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  dio: ^5.7.0
  logger: ^2.4.0
  either_dart: ^1.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
